server:
  port: 8081
spring:
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          # 最大连接数(使用负值表示没有限制) 默认为 8
          max-active: 10
          # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
          max-wait: -1
          # 最大空闲连接 默认为 8
          max-idle: 8
          # 最小空闲连接 默认为 0
          min-idle: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=pop-world
    username: postgres
    password: 5995
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl